# Generated by Django 2.2.5 on 2020-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200103_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='rooms_photos'),
        ),
    ]
